### PR TITLE
updated dependency version to support latest AppStore Connect APIs

### PR DESCRIPTION
**Pull request by suculent**

### CODE REVIEW

**Comment by suculent** [comment]
Thanks, however this is more like a workaround. It does not seem to automatically take new versions in account... such fix should be done a way it won’t be needed next time. 

Odesláno z iPhonu

18. 9. 2018 v 19:15, Felix Krause <notifications@github.com>:

**Comment by KrauseFx** [comment]
Thanks @suculent, can you tell us more about how this would be possible by submitting a new issue? From what I understand, Heroku will always use the `Gemfile.lock`, so we'll have to always update it

**Comment by suculent** [comment]
I didn’t realize that. What if the Gemfile.lock is not present in the repository? It should be re-created by heroku pre-commit hook. 

This change was not mentally in the lockfile, but in Gemfile itself only. Rest is process-based. 

Odesláno z iPhonu

20. 9. 2018 v 19:36, Felix Krause <notifications@github.com>:

**Comment by KrauseFx** [comment]
Yah that makes sense. So we'll leave it as is for now then

**Pull request merged**
