### PR TITLE
Added support for new App Store Connect TestFlight API

### LINKED ISSUE #244: HTTP ERROR 410 Gone
Hello, since yesterday Apple returns error 410 when accessing form boarding on path /v2/providers/1111111/apps/2222222222/groups

```
2019-04-05T11:47:37.149619+00:00 app[web.1]: [4] ! Unable to load application: Spaceship::UnexpectedResponse: <html>
2019-04-05T11:47:37.149645+00:00 app[web.1]: <head>
2019-04-05T11:47:37.149647+00:00 app[web.1]: <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
2019-04-05T11:47:37.149649+00:00 app[web.1]: <title>Error 410 Gone</title>
2019-04-05T11:47:37.149650+00:00 app[web.1]: </head>
2019-04-05T11:47:37.149652+00:00 app[web.1]: <body><h2>HTTP ERROR 410</h2>
2019-04-05T11:47:37.149653+00:00 app[web.1]: <p>Problem accessing /v2/providers/1111111111/apps/2222222222/groups. Reason:
2019-04-05T11:47:37.149655+00:00 app[web.1]: <pre>    Gone</pre></p>
2019-04-05T11:47:37.149656+00:00 app[web.1]: </body>
2019-04-05T11:47:37.149657+00:00 app[web.1]: </html>
2019-04-05T11:47:37.149719+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.4.0/bin/puma)
2019-04-05T11:47:37.149795+00:00 app[web.1]: Spaceship::UnexpectedResponse: <html>
2019-04-05T11:47:37.149797+00:00 app[web.1]: <head>
2019-04-05T11:47:37.149799+00:00 app[web.1]: <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
2019-04-05T11:47:37.149800+00:00 app[web.1]: <title>Error 410 Gone</title>
2019-04-05T11:47:37.149801+00:00 app[web.1]: </head>
2019-04-05T11:47:37.149803+00:00 app[web.1]: <body><h2>HTTP ERROR 410</h2>
2019-04-05T11:47:37.149804+00:00 app[web.1]: <p>Problem accessing /v2/providers/111111111/apps/222222222222/groups. Reason:
2019-04-05T11:47:37.149806+00:00 app[web.1]: <pre>    Gone</pre></p>
2019-04-05T11:47:37.149807+00:00 app[web.1]: </body>
2019-04-05T11:47:37.149808+00:00 app[web.1]: </html>
```

### LINKED ISSUE #245: Fastlane update to 2.120
Are there any plans to update the Fastlane version to 2.120 when [#14545](https://github.com/fastlane/fastlane/pull/14545) is uploaded to [Fastlane RubyGem](https://rubygems.org/gems/fastlane)?

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #244
Fixes #245
Fixes https://github.com/fastlane/fastlane/issues/14635

### CODE REVIEW

**Comment by clippka** [comment]
IMHO app/services/.boarding_service.rb.swp was wrongly added?

**Comment by joshdholtz** [comment]
@clippka lol, you are 100% correct 😱 Will fix

**Comment by jabeler** [comment]
Working here for me. Thanks! 👍

**Comment by AlexeyLi** [comment]
I just tried to deploy the latest version of the boarding app and it shows that I was successfully added as a new tester, but I didn't get an invite email and I'm not able to find myself when I check on TestFlight. I think this block of code doesn't get executed 
`client = Spaceship::ConnectAPI::Base.client
      response = client.request(:post) do |req|
        req.url("bulkBetaTesterAssignments")
        req.body = body.to_json
        req.headers['Content-Type'] = 'application/json'`, I tried adding logs with `response.status` and `response.body` to verify and I don't see them in the console either.

**Comment by janpio** [comment]
(Best create a new issue and link to this PR, otherwise this might get lost @AlexeyLi)

**Pull request merged**
